language: java

jdk:
  - openjdk8

cache:
  directories:
    - "$HOME/.m2"

script: 
  - ./mvnw clean install -B

after_success:
  - ./mvnw -B jacoco:report coveralls:report -DrepoToken=$COVERALLS_TOKEN